## 'makeCacheMatrix' provides an interface for storing and
## retrieving a matrix and its inverse.  
## 'cacheSolve' will find the inverse, retrieving a stored version
## if possible.
##
## Usage:  If x is a square, invertible matrix, set it with
##    mat <- makeCacheMatrix(x)
## Then call for the inverse using
##    cacheSolve(mat)
## If the inverse has already been computed (and mat has not changed),
## cacheSolve will return the stored inverse.  Otherwise, it will compute
## and store the inverse of mat.
##
## Both are similar to the sample code on caching the mean
## of a vector.

## Provides methods for storing and retrieving a matrix and
## its inverse:
makeCacheMatrix <- function(x = matrix()) {
  # Note that 'x' will reprsent the matrix, and 'matinv' the inverse
  matinv <- NULL
  setmatrix <- function(y) {
    # A "global" assignment for x, so it will be preserved
    x <<- y
    matinv <<- NULL  # Reset matinv whenever matrix changes.
  }
  getmatrix <- function() { x }
  setinverse <- function(y) {matinv <<- y }
  getinverse <- function() { matinv }
  # Return the list:
  list(setmatrix = setmatrix, getmatrix = getmatrix, 
       setinverse = setinverse, getinverse = getinverse)
}


## Takes an object generated by makeCacheMatrix, and returns
## its inverse, either from cache (if present) or using solve.
cacheSolve <- function(x, ...) {
  # Return a matrix that is the inverse of 'x'
  matinv <- x$getinverse()
  if (!is.null(matinv)) {
    message("getting cached data") # notify that we found cached inverse
    return(matinv) # Return this value and exit
  } 
  # Otherwise, find and store the inverse:
  matinv <-solve(x$getmatrix())
  x$setinverse(matinv)
  matinv
}
